In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
a = [1,2,3]
print(a)

[1, 2, 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
z = np.zeros((2,3)) #2 rows and 3 columns
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
one = np.ones(4)
print(one)

[1. 1. 1. 1.]


In [8]:
f = np.full((2,2), 7)
print(f)

[[7 7]
 [7 7]]


In [9]:
r = np.arange(0,10,2)  # [0 2 4 6 8]
print(r)

[0 2 4 6 8]


In [10]:
L = np.linspace(0,1,6)  # [0.   0.25 0.5  0.75 1.  ]
print(L)
## How linspace works: It divides the interval [0, 1] into 4 equal parts (since we want 5 points) and returns those points.

[0.  0.2 0.4 0.6 0.8 1. ]


In [11]:
# identity, eye matrix: 1s on the diagonal, 0s elsewhere
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# random: uniform distribution between 0 and 1
x = np.random.rand(3,2)   # uniform [0,1)
print(x)

[[0.81816768 0.2968121 ]
 [0.57955004 0.17609914]
 [0.92231489 0.27187503]]


In [13]:
# empty (uninitialized, faster): values will be whatever is in memory
E = np.empty((2,3))
print(E)

[[0.81816768 0.2968121  0.57955004]
 [0.17609914 0.92231489 0.27187503]]


In [14]:
# Create a 3x3 identity matrix. : 1s on the diagonal, 0s elsewhere
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# ndim number of dimensions
# shape tuple of axis lengths
# size number of elements
# dtype data type
# itemsize bytes per element
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)

2 (2, 3) 6 int32 4


In [16]:
# Print attributes for array of floats np.array([1.,2.,3.])
a = np.array([1.5,2.,3.])
print(a)
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)

[1.5 2.  3. ]
1 (3,) 3 float64 8


In [17]:
arr = np.arange(10)
sub = arr[2:7:2]   # start:stop:step stop is exclusive
print(arr)
print(sub)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [18]:
mat = np.arange(12).reshape(3,4)
print(mat)
row1 = mat[1]   # row 1
print(row1)
cell = mat[2,3]
print(cell)
col2 = mat[:,2]
print(col2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
11
[ 2  6 10]


In [19]:
# copy()
arr = np.array([1,2,3])
arr_copy = arr.copy()
arr_copy[0] = 100
print(arr)
print(arr_copy)

[1 2 3]
[100   2   3]


In [20]:
x = np.array([1,2,3], dtype=np.int32)
xf = x.astype(np.float32)
print(x)
print(xf)
print(xf.dtype)

[1 2 3]
[1. 2. 3.]
float32


In [21]:
x = np.array([1,2,3])
y = np.array([10,20,30])
print(x + y)
print(x * 2)
print(np.sin(x))

[11 22 33]
[2 4 6]
[0.84147098 0.90929743 0.14112001]


In [22]:
M = np.ones((3,4))
# print(M)
v = np.array([1,2,3,4])
# print(v)
print(M + v)  # v broadcast across rows

w = np.array([10,20,30]).reshape(3,1)
# print(w)
print(w + v)  # shapes (3,1) and (4,) broadcast to (3,4)

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [23]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.mean(data))
print(np.mean(data, axis=0))
print(np.std(data))
print(np.var(data))
print(np.median(data))
print(np.percentile(data, 50))
print(np.corrcoef(data[0], data[1]))

5.0
[4. 5. 6.]
2.581988897471611
6.666666666666667
5.0
5.0
[[1. 1.]
 [1. 1.]]


In [3]:
a = np.array([1,2,3,4,5])
b = np.array([3,2,1,4,6])

print(a > 2)                            # boolean array
print(a == b)                           # compare arrays
print(np.logical_and(a>1, a<5))         # AND
print(np.logical_or(a==2, b==6))        # OR
print(np.all(a<6), np.any(a==3))        # reduce to single bool

[False False  True  True  True]
[False  True False  True False]
[False  True  True  True False]
[False  True False False  True]
True True
