1. Why NumPy
- NumPy gives fast, memory-efficient arrays.
- It replaces slow Python loops with vectorized operations.
- You use array math directly on data.

- install numpy using **pip install numpy**

In [7]:
import numpy as np  # standard import

In [6]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [15]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
z = np.zeros((2,3))    # all zeros
print(z)
print("-"*20)
o = np.ones((1,3))     # all ones
print(o)
print("-"*20)
f = np.full((5,10),7)  # filled with constant 7
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
--------------------
[[1. 1. 1.]]
--------------------
[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


In [27]:
arr = np.arange(0,11) 
print(arr)
r = np.arange(0,10,2)     # start,stop(exclusive),step
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 2 4 6 8]


In [33]:
L = np.linspace(2,10,5)    # 5 evenly spaced values between 0–1
print(L)

[ 2.  4.  6.  8. 10.]


In [39]:
# Identity matrix or eye
I = np.eye(4)
print(I)

i = np.identity(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [87]:
# Random arrays
x = np.random.rand(3,2)   # random floats in [0,1)
print(x)

[[0.45051225 0.50953754]
 [0.61734334 0.7940428 ]
 [0.6064723  0.08626938]]


In [95]:
E = np.empty((2,3))       # uninitialized values (faster)
print(E)

[[0.45051225 0.50953754 0.61734334]
 [0.7940428  0.6064723  0.08626938]]


In [108]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

2
(3, 4)
12
int32
4


In [129]:
# arr = np.arange(10)
# print(arr)
# sub = arr[2:9:2]       # start:stop:step
# print(sub)

mat = np.arange(12).reshape(3,4) # 3 rows, 4 columns
print(mat)
print(mat[1])           # 2nd row
print(mat[2,3])         # specific cell
print(mat[:,2])         # full column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
11
[ 2  6 10]


In [147]:
x = np.array([1,2,3], dtype=np.int32) # 32 bit integer
xf = x.astype(np.float64) # 64 bit float
print(x.dtype)
print(xf)
print(xf.dtype)

int32
[1. 2. 3.]
float64


In [154]:
x = np.array([1,2,3])
y = np.array([10,20,30])

print(x + y)         # elementwise add
print(x * y)         # scalar multiply
print(np.sin(x))     # elementwise sine

[11 22 33]
[10 40 90]
[0.84147098 0.90929743 0.14112001]


In [165]:
# M = np.ones((3,4))
# print(M)
v = np.array([1,2,3,4])
print(v)
# print(M + v)

w = np.array([10,20,30]).reshape(3,1)
print(w)

print(w + v)


[1 2 3 4]
[[10]
 [20]
 [30]]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [170]:
M = np.arange(12).reshape(3,4)
print(M)
print(M.sum())
print(M.sum(axis=0)) #by column
print(M.sum(axis=1)) #by row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


In [184]:
a = np.array([1,2,3,4,5])
b = np.array([3,2,1,4,6])
# print(a>2)
# print(a == b)
# print(np.logical_and(a>2, b>2))
# print(np.logical_or(a>2, b>2))
print(np.all(a>2), np.any(a>3))        # reduce to single bool

False True


In [197]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data)
print(np.corrcoef(data[0],data[1]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1.]
 [1. 1.]]


In [206]:
x = np.array([10,20,30,40])
print(x[[3,1]])     # specific indices
print(x[x>15])      # filter by condition

[40 20]
[20 30 40]


In [219]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)
print("-----------------------------")
print(np.concatenate([a,b], axis=0))  # vertical join
print("-----------------------------") # vertical join vstack both are same
print(np.vstack([a,b])) 
print("-----------------------------")
print(np.hstack([a,b])) 

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
-----------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-----------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-----------------------------
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [267]:
print(np.random.seed(0))
print(np.random.randint(0,10,7))

None
[5 0 3 3 7 9 3]
